[files]
; 注意遍历目录时_开头的文件或文件夹将会跳过

; 其他dll放在这个目录下，会尝试全部加载，可能有兼容问题
dlls = mod_engine/dlls

; mods目录，可以将多个mod分开放在里面，会按文件夹名顺序加载，重复的文件先加载的生效
mods = mod_engine/mods

; 加载存档，关闭存档验证，可以加载其他玩家的存档
save = mod_engine/saves/S0000.sl2

; 替换所有过场动画，主要用于跳过过场动画，防止人物mod导致的崩溃
cutscene = mod_engine/skip.cutscenebnd.dcx


[memory]
; 修改游戏内存，格式：偏移地址 = 修改的十六进制字节序列

; 无限金币 9999
66DA63 = C7 41 7C 0F 27 00 00 C3

; 跳过厂商LOGO
E1B51B = 75

; 自动拾取敌人死亡掉落物品
91C606 = B0 01

; 自动切换锁定目标
9C7B70 = 90 90 90 90

; 屏蔽鼠标移动切换锁定目标
9C7DBB = EB 0F

; 保持锁定状态，游戏内打开固定目标自动切换，可以保持自动锁定
9C7D0D = 2E
9C7D19 = 22
9C7D20 = 1B

; 按下锁定键没有目标时不重置视角
9C7D27 = 00

; 纸人上限99
10BF373 = EB

; 持有物品数量只增加不减少
;7A741E = 39 7B 08 0F 4F 7B 08 89 7B 08

; 调整FOV，值按4的倍数修改，默认值是04，建议可选值08、0C、10
;73C690 = 04

; Tab键切换自由视角
;83BE69 = E8 99 06 DB 01


[debug_menu]
; 开启debug menu支持，游戏内按键盘Insert打开菜单
enable = 1

; 字体文件路径
font_path = mod_engine/debugfont.ttf

; 字体大小
font_size = 18

; 菜单选中项字体颜色RGB值
color = 0xC10066


[key_remap]
; 按键重映射，格式：游戏事件16进制ID_旧16进制键值 = 新16进制键值
; D2D映射只能有一个新键值，A2A映射必须有两个新键值并用下划线连接
; 在[logs]中开启key_remap可以输出按键映射信息

; 开发者菜单NPC控制
; -后的是注释，无效果，可以不写，表示默认的手柄按键和对应的动作
; 按键对应的动作可以用参数编辑器在NpcParam中修改
25f_36----up_700 = 58    ; R
260_37--down_701 = 7E    ; 空格键
261_38--left_702 = 66    ; F
262_39-right_703 = 67    ; G
263_3e----Y_3007 = 48    ; 2
264_3c----B_3006 = 57    ; E
265_3b----X_3004 = 47    ; 1
266_3d----A_3005 = 55    ; Q
267_3f---LB_3001 = 0     ; 鼠标左键
268_40---RB_3000 = 1     ; 鼠标右键
269_41---LT_3003 = 71    ; Z
26a_42---RT_3002 = 72    ; X

; 开发者菜单自由视角控制
; 如需Tab键切换自由视角，在[memory]中开启83BE69位置的补丁
; 264_3c = 57 ; E，向右滚动相机，和开发者菜单NPC控制相同，不要重复设置
; 266_3d = 55 ; Q，向左滚动相机，和开发者菜单NPC控制相同，不要重复设置
314_3 = 65_63 ; D_A，左右移动相机
313_4 = 56_64 ; W_S，前后移动相机
317_6 = C1_C0 ; 右方向键_左方向键，左右旋转相机
318_7 = BE_C3 ; 上方向键_下方向键，上下旋转相机
315_c = 58_66 ; R_F，上下移动相机
1c3_40 = 74   ; V，按住快速移动相机
1c4_3f = 7E   ; 空格键，按住慢速移动相机

; 一键流派招式，66是F
;232_40 = 66
;234_3f = 66


[npc_anim_change]
; 被控制的NPC动作速度倍率
anim_speed = 1.2

; 改变用开发者菜单控制的NPC动作
config_path = mod_engine/npc_anim_example.ini

; 运行时自动重新加载修改过的配置文件
config_runtime_reload = 0


[player_skill_change]
; 改变玩家的义手忍具和流派招式
config_path = mod_engine/player_skill_example.ini

; 运行时自动重新加载修改过的配置文件
config_runtime_reload = 0


[logs]
; 将输出信息打印到控制台而不是mod_engine.log中
console = 0

; 按P输出开发者菜单文本信息
debug_menu = 1

; 输出游戏按键绑定信息
key_remap = 0

; 输出玩家装备义手忍具或流派招式时的ID信息
equip_skill = 0

; 输出NPC控制动作ID变换信息
npc_anim_change = 0


[virtual_alloc_size]
; 调整各模块VirtualAlloc的内存大小，单位是字节，注释是默认值
; 在使用某些地图mod时，MO模块可能内存不足导致游戏崩溃，可以适当增加MO模块的内存分配

; MAIN = 0x60100000
; MENU = 0xf000000
; GFX = 0x60000000
; GFXTEMP = 0x4000000
; GFX_Gparam = 0x600000
; INGAME = 0x1000000
; TEMP = 0x500000
; CORERES = 0x6400000
; MO = 0x7400000
MO = 0xF400000
; NETWORK = 0x1b00000
; LUA = 0xc00000
; HAVOK = 0x32000000
; DEBUG = 0x7400000
; GFX_SystemShared = 0x100000
; GFX_GraphicsPrivate = 0x100000
