; 格式：义手忍具槽位_辅助按键 = 义手忍具或流派招式ID
; 当处于此义手忍具槽位，按住辅助按键，使用义手忍具或流派招式时，触发配置的义手忍具或流派招式
; 义手忍具槽位用1,2,3表示
; 辅助按键如果是字母按键可以直接写字母，不区分大小写，其他用Windows虚拟键值表示，如空格键是32
; 流派招式ID范围[5000, 10000)
; 义手忍具ID范围[70000, 100000)
; 可以开启[logs]下的equip_skill来查看义手忍具或流派招式ID
; 如果义手忍具和流派招式的触发条件相同，可以用_分隔两者写成一条配置
; 当同时按下多个辅助按键，在上面的配置优先

1_w = 5100
1_w = 78400
1_s = 7000
1_a = 5500_73200

2_w = 72300
2_a = 73300

3_32 = 7100
